name: pastisnb
channels:
    - default
dependencies:
    - python=3.9
    - pip
    - pip:
        - sphinx
        - numpy
        - scipy
        - sklearn
        - matplotlib
        - jupyter-book
        - iced
        - pastis
        - joblib
        - cython
